--Calculo de la reducción de 8 semanas a una fecha ingresada en MSSQL Server
SET DATEFORMAT YMD
DECLARE @FECHA CHAR(10) = '2017-09-04'
DECLARE @DIADELASEMANA VARCHAR(10) = DATENAME(DW,@FECHA)
DECLARE @NUMERODELASEMANA INT = DATEPART(DW,@FECHA)
--Se restan 27 dias porque: 8(semanas) * 7(dias) = 56 pero los años biciestos son 29 (117/4) --esto se desfasaría cada 4 años
DECLARE @FECHANUMERO INT = 1*365*117+CONVERT(INT,(DATEPART(dayofyear,@FECHA)))-27
DECLARE @FECHAINICIAL DATE = CONVERT(VARCHAR,YEAR(@FECHANUMERO))+'/'+ CONVERT(VARCHAR,MONTH(@FECHANUMERO))+'/'+ CONVERT(VARCHAR,DAY(@FECHANUMERO))

PRINT @FECHAINICIAL
PRINT @FECHA

DECLARE @DIAS_A_RESTAR INT = CONVERT(INT,(DATEPART(DAY,@FECHA)))-1
PRINT @DIAS_A_RESTAR

--SE SUMA +28 POR EL DESFASE DE LOS AOS BICIESTOS
DECLARE @FECHAPRIMERO INT = 1*365*117+CONVERT(INT,(DATEPART(dayofyear,@FECHA)))-@DIAS_A_RESTAR+28
DECLARE @SEMANA_PRIMERO DATE = CONVERT(VARCHAR,YEAR(@FECHAPRIMERO))+'/'+ CONVERT(VARCHAR,MONTH(@FECHAPRIMERO))+'/'+ CONVERT(VARCHAR,DAY(@FECHAPRIMERO))
DECLARE @SEMANA_ANIO INT = DATEPART(WK,@SEMANA_PRIMERO)

--PRINT @FECHAPRIMERO
PRINT @SEMANA_PRIMERO
--PRINT @SEMANA_ANIO
PRINT 'El mes es: ' + DATENAME(MONTH,@FECHA) + ' y la Semana es: ' + CONVERT(VARCHAR,(DATEPART(WK,@FECHA)-@SEMANA_ANIO+1))
--DECLARE @SEMANA_PRIMERO INT = 
--DECLARE @DIASDELASEMA INT = CONVERT(INT,(DATEPART(dayofyear,@FECHA)))-@DIAS
--DECLARE @SEMANAINICIO INT = CONVERT(INT,DATEPART(WEEK, @FECHA))-8
--PRINT @SEMANAINICIO
--DECLARE @DIADEINICIO VARCHAR(10) = DATEPART(WEEKDAY,@SEMANAINICIO)
--PRINT @DIADEINICIO
--PRINT YEAR(1*365*118+CONVERT(INT,(DATEPART(dayofyear,@FECHA)))-@DIAS)
--PRINT MONTH(30)
--PRINT 
--PRINT CONVERT(DATE,'2016' + @DIASDELASEMA)
--PRINT GETDATE() -@DIAS - @REPORTE
